# Background Research 

In an overview, the word “unbanked” defines people who do not own any form of bank account, while “underbanked” characterizes those who have a bank account but do not have access to mainstream bank services such as credit and loans. In a survey conducted by the Federal Deposit Insurance Corporation in 2017, 53% of the unbanked population in the US reported insufficient financial means to maintain a bank account, while 30% cited “Don’t trust banks”. The lack of credit score results in inability to access common bank services such as loans and credit cards. As a result, many resorts to more expensive options when seeking financial services as simple as cashing out a check. When caught in a financial emergency, people are forced to take out at unaffordable high interest rates and therefore the cycle worsens. 
In expanding financial inclusion, Home Credit aims to create lines of credit specifically for the unbanked population. The main company objective is to not only build trust with clients, but also have good risk management strategies. To minimize risks of credit default, our objective is to create an algorithm on loan application approval predicting potential of repayment. However, the main challenge to this task is that 70% of Home Credit clients are first-time borrowers. As a result, there is limited record on client credit history, which serves as an important indicator in conventional credit underwriting. In a finance summit, Home Credit has stated that the key to risk management in this client pool rests in two aspects.  One is client’s repayment capability and understanding how much of an instalment he or she can afford. The other is to identify fraudsters who intend to loan with no intentions of repaying. 

